<?php $pageTitle='Combo Offers — RCS Admin';$currentAdmPage='combo-offers';include __DIR__.'/layout.php'; ?>
<div class="adm-pt">Combo Offers Manager</div><div class="fsec combo-admin"><div class="combo-admin-head"><p>Create homepage combo banners and link them to dedicated offer pages.</p><button class="btn btn-blue" onclick="openComboForm()">+ New Combo Offer</button></div><div id="comboAdminList"></div></div>
<div class="adm-dialog" id="comboFormModal" hidden><div class="adm-dialog-backdrop" onclick="closeComboForm()"></div><section class="adm-dialog-panel combo-admin-dialog"><button class="custom-quote-close" onclick="closeComboForm()">×</button><h2 id="comboFormTitle">New Combo Offer</h2><form id="comboForm" onsubmit="saveCombo(event)"><input type="hidden" name="id"><div class="combo-form-grid"><label>Title<input class="fi" name="title" required></label><label>Slug<input class="fi" name="slug"></label><label>Badge<input class="fi" name="badge" placeholder="Business starter pack"></label><label>Layout<select class="fi" name="layout_slot"><option value="large">Large</option><option value="wide">Wide</option><option value="square">Square</option></select></label><label>Regular Total<input class="fi" type="number" min="0" step=".01" name="regular_price"></label><label>Combo Price<input class="fi" type="number" min="0" step=".01" name="combo_price" required></label><label>CTA Text<input class="fi" name="cta_text" value="View Offer"></label><label>Sort Order<input class="fi" type="number" name="sort_order" value="0"></label></div><label>Short Description<textarea class="fi" name="short_description"></textarea></label><label>Full Description<textarea class="fi" name="description" rows="4"></textarea></label><label>Banner Image<div class="combo-upload-row"><input class="fi" name="banner_image" id="comboBanner"><input type="file" id="comboFile" accept="image/*"><button type="button" class="btn btn-outline" onclick="uploadComboImage()">Upload</button></div></label><fieldset><legend>Included Products</legend><div id="comboProducts" class="combo-product-checks"></div></fieldset><label><input type="checkbox" name="show_on_home" checked> Show on homepage</label><label><input type="checkbox" name="is_active" checked> Active</label><div class="adm-dialog-actions"><button type="button" class="btn btn-light" onclick="closeComboForm()">Cancel</button><button class="btn btn-blue">Save Combo</button></div></form></section></div>
<script>
const COMBO_CSRF='<?= htmlspecialchars($csrf??'') ?>';let COMBOS=[],COMBO_PRODUCTS=[];const ce=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
async function loadCombos(){const r=await fetch('/admin/api/combo-offers').then(r=>r.json());if(!r.ok)return;COMBOS=r.offers||[];COMBO_PRODUCTS=r.products||[];document.getElementById('comboAdminList').innerHTML=COMBOS.length?COMBOS.map(o=>`<article class="combo-admin-row"><img src="${ce(o.banner_image||'')}" onerror="this.style.visibility='hidden'"><div><b>${ce(o.title)}</b><small>${ce(o.layout_slot)} · ₹${Number(o.combo_price).toLocaleString('en-IN')} · ${Number(o.item_count)} products · ${Number(o.is_active)?'Active':'Inactive'}</small></div><div><a class="btn btn-outline btn-sm" href="/combo/${ce(o.slug)}" target="_blank">View</a><button class="btn btn-outline btn-sm" onclick="editCombo(${Number(o.id)})">Edit</button><button class="btn btn-outline btn-sm" onclick="deleteCombo(${Number(o.id)})">Delete</button></div></article>`).join(''):'<div class="adm-empty">No combo offers yet.</div>';}
function productChecks(selected=[]){document.getElementById('comboProducts').innerHTML=COMBO_PRODUCTS.map(p=>`<label><input type="checkbox" name="product_ids[]" value="${Number(p.id)}" ${selected.includes(Number(p.id))?'checked':''}> ${ce(p.name)}</label>`).join('');}
function openComboForm(){const f=document.getElementById('comboForm');f.reset();f.elements.id.value='';productChecks();document.getElementById('comboFormTitle').textContent='New Combo Offer';document.getElementById('comboFormModal').hidden=false;}
function closeComboForm(){document.getElementById('comboFormModal').hidden=true;}
async function editCombo(id){const r=await fetch(`/admin/api/combo-offers/${id}`).then(r=>r.json());if(!r.ok)return;const f=document.getElementById('comboForm'),o=r.offer;for(const [k,v] of Object.entries(o))if(f.elements[k]&&f.elements[k].type!=='checkbox')f.elements[k].value=v??'';f.elements.id.value=o.id;f.elements.show_on_home.checked=Number(o.show_on_home)===1;f.elements.is_active.checked=Number(o.is_active)===1;productChecks((o.items||[]).map(x=>Number(x.product_id)));document.getElementById('comboFormTitle').textContent='Edit Combo Offer';document.getElementById('comboFormModal').hidden=false;}
async function saveCombo(e){e.preventDefault();const f=e.currentTarget,d=Object.fromEntries(new FormData(f).entries());d.product_ids=new FormData(f).getAll('product_ids[]');d.show_on_home=f.show_on_home.checked?1:0;d.is_active=f.is_active.checked?1:0;const id=f.elements.id.value;const r=await fetch(id?`/admin/api/combo-offers/${id}`:'/admin/api/combo-offers',{method:id?'PUT':'POST',headers:{'Content-Type':'application/json','X-CSRF-TOKEN':COMBO_CSRF},body:JSON.stringify(d)}).then(r=>r.json());if(!r.ok)return alert(r.msg||'Could not save');closeComboForm();loadCombos();}
async function uploadComboImage(){const file=document.getElementById('comboFile').files[0];if(!file)return;const fd=new FormData();fd.append('image',file);const r=await fetch('/admin/api/combo-offers/upload',{method:'POST',headers:{'X-CSRF-TOKEN':COMBO_CSRF},body:fd}).then(r=>r.json());if(r.ok)document.getElementById('comboBanner').value=r.path;else alert(r.msg);}
async function deleteCombo(id){if(!await adminConfirm('Delete this combo offer?'))return;await fetch(`/admin/api/combo-offers/${id}`,{method:'DELETE',headers:{'X-CSRF-TOKEN':COMBO_CSRF}});loadCombos();}loadCombos();
</script></div></div></div></body></html>
