<?php $comboEditId=(int)($comboEditId??0);$pageTitle=($comboEditId?'Edit':'Add').' Combo Offer — RCS Admin';$currentAdmPage='combo-offers';include __DIR__.'/layout.php'; ?>
<div class="adm-page-head"><div><div class="adm-pt"><?= $comboEditId?'Edit':'Add New' ?> Combo Offer</div><p>Build a complete bundle using catalog products and custom items.</p></div><a class="btn btn-outline" href="/admin/combo-offers">← Back to Combo Offers</a></div>
<form id="comboForm" class="combo-full-form"><input type="hidden" name="id" value="<?= $comboEditId ?>"><input type="hidden" name="banner_image"><section class="fsec"><h2>Basic Information</h2><div class="combo-form-grid"><label>Title *<input class="fi" name="title" required><span class="field-visibility"><label><input type="checkbox" name="show_title_home" checked> Homepage Banner</label><label><input type="checkbox" name="show_title_detail" checked> Detail Page</label></span></label><label>Slug *<input class="fi" name="slug" required><small>Generated automatically; you can edit it manually.</small></label></div></section>
<section class="fsec"><div class="combo-section-head"><div><h2>Available Products</h2><p>Choose a category, then add products. Previously selected products remain selected.</p></div><select class="fi" id="categoryFilter"><option value="">Select Product Category</option></select></div><div id="availableProducts" class="combo-catalog-grid"></div><h3>Selected Products</h3><div id="selectedProducts" class="combo-selected-list"><div class="adm-empty">No products selected.</div></div></section>
<section class="fsec"><div class="combo-section-head"><div><h2>Custom Items</h2><p>Add non-catalog items with per-unit price and quantity.</p></div><button class="btn btn-outline" type="button" onclick="addCustomItem()">+ Add Custom Item</button></div><div id="customItems" class="combo-custom-list"></div></section>
<section class="fsec combo-price-builder"><div><span>Products &amp; Items Subtotal</span><strong id="comboSubtotal">₹0</strong></div><div class="combo-form-grid"><label>Discount %<input class="fi" type="number" min="0" max="100" step=".01" name="discount_percent" value="0" oninput="priceFromDiscount()"></label><label>Offer Price *<input class="fi" type="number" min=".01" step=".01" name="combo_price" required oninput="discountFromPrice()"></label></div><small id="comboSaving"></small></section>
<section class="fsec"><h2>Frontend Content</h2><div class="combo-form-grid"><label>Badge<input class="fi" name="badge"><span class="field-visibility"><label><input type="checkbox" name="show_badge_home" checked> Homepage Banner</label><label><input type="checkbox" name="show_badge_detail" checked> Detail Page</label></span></label><label>Homepage Position<select class="fi" name="layout_slot" id="layoutSlot"><option value="large">1. Large Square — Left</option><option value="wide">2. Wide Banner — Top Right</option><option value="square_3">3. Square Banner — Bottom Right 1</option><option value="square_4">4. Square Banner — Bottom Right 2</option></select><small id="positionHelp">One active offer can occupy each position.</small></label><label>CTA Text<input class="fi" name="cta_text" value="View Offer"><span class="field-visibility"><label><input type="checkbox" name="show_cta_home" checked> Homepage Banner</label><label><input type="checkbox" name="show_cta_detail" checked> Detail Page</label></span></label></div><label>Short Description<textarea class="fi" name="short_description" rows="3"></textarea><span class="field-visibility"><label><input type="checkbox" name="show_short_description_home" checked> Homepage Banner</label><label><input type="checkbox" name="show_short_description_detail" checked> Detail Page</label></span></label><label>Long Description<textarea class="fi" name="description" rows="5"></textarea><span class="field-visibility"><label><input type="checkbox" name="show_description_home" checked> Homepage Banner</label><label><input type="checkbox" name="show_description_detail" checked> Detail Page</label></span></label><label>Banner Image<div class="combo-auto-upload"><input type="file" id="bannerFile" accept="image/jpeg,image/png,image/webp"><span id="uploadStatus">Select image to upload automatically.</span><img id="bannerPreview" hidden alt="Banner preview"></div></label></section>
<div class="combo-form-actions"><span id="formError"></span><a class="btn btn-light" href="/admin/combo-offers">Cancel</a><button class="btn btn-blue" id="saveButton">Save Combo Offer</button></div></form>
<script>
const EDIT_ID=<?= $comboEditId ?>,CSRF='<?= htmlspecialchars($csrf??'') ?>';let PRODUCTS=[],CATEGORIES=[],SELECTED=new Map(),customSeq=0,slugManual=EDIT_ID>0,syncing=false;
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m])),money=n=>'₹'+Number(n||0).toLocaleString('en-IN',{maximumFractionDigits:2}),slugify=s=>String(s).normalize('NFKD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'');
function product(id){return PRODUCTS.find(x=>Number(x.id)===Number(id))}function tier(p,q){return (p?.tiers||[]).find(x=>Number(x.quantity)===Number(q))}
function renderAvailable(){const cat=Number(document.getElementById('categoryFilter').value||0),box=document.getElementById('availableProducts');if(!cat){box.innerHTML='<div class="adm-empty">Select a category to view products.</div>';return}const list=PRODUCTS.filter(p=>Number(p.category_id)===cat);box.innerHTML=list.length?list.map(p=>`<article class="combo-catalog-card"><img src="${esc(p.thumbnail||'/assets/images/RCS%20PRINT%20LOGO.png')}" alt=""><div><strong>${esc(p.name)}</strong><small>${esc(p.category_name||'')}</small></div><button type="button" class="btn btn-outline btn-sm" ${SELECTED.has(Number(p.id))?'disabled':''} onclick="addProduct(${Number(p.id)})">${SELECTED.has(Number(p.id))?'Added':'Add'}</button></article>`).join(''):'<div class="adm-empty">No products in this category.</div>';}
function addProduct(id){const p=product(id);if(!p||SELECTED.has(id)||!(p.tiers||[]).length)return;SELECTED.set(id,{product_id:id,quantity:Number(p.tiers[0].quantity)});renderAvailable();renderSelected()}
function removeProduct(id){SELECTED.delete(id);renderAvailable();renderSelected()}
function setProductQty(id,q){SELECTED.get(id).quantity=Number(q);renderSelected()}
function renderSelected(){const box=document.getElementById('selectedProducts');box.innerHTML=SELECTED.size?[...SELECTED.values()].map(x=>{const p=product(x.product_id),t=tier(p,x.quantity);return `<article class="combo-selected-row"><img src="${esc(p.thumbnail||'/assets/images/RCS%20PRINT%20LOGO.png')}" alt=""><strong>${esc(p.name)}</strong><select class="fi" onchange="setProductQty(${Number(p.id)},this.value)">${(p.tiers||[]).map(v=>`<option value="${Number(v.quantity)}" ${Number(v.quantity)===Number(x.quantity)?'selected':''}>${Number(v.quantity).toLocaleString('en-IN')}</option>`).join('')}</select><b>${money(t?.price)}</b><button type="button" class="btn btn-outline btn-sm" onclick="removeProduct(${Number(p.id)})">Remove</button></article>`}).join(''):'<div class="adm-empty">No products selected.</div>';recalculate()}
function addCustomItem(x={}){const id=++customSeq;document.getElementById('customItems').insertAdjacentHTML('beforeend',`<article class="combo-custom-row" data-custom="${id}"><div class="combo-custom-thumb"><img src="${esc(x.thumbnail_path||'/assets/images/RCS%20PRINT%20LOGO.png')}" alt=""><input type="hidden" data-f="thumbnail_path" value="${esc(x.thumbnail_path||'')}"><input type="file" accept="image/jpeg,image/png,image/webp" onchange="uploadCustom(this)"></div><input class="fi" data-f="item_name" value="${esc(x.item_name||'')}" placeholder="Item name"><input class="fi" type="number" min="1" data-f="quantity" value="${Number(x.quantity||1)}" placeholder="Quantity" oninput="recalculate()"><input class="fi" type="number" min=".01" step=".01" data-f="item_price" value="${Number(x.item_price||'')||''}" placeholder="Unit price" oninput="recalculate()"><textarea class="fi" data-f="description" rows="3" placeholder="Specifications, one per line">${esc(x.description||'')}</textarea><button type="button" class="btn btn-outline btn-sm" onclick="this.closest('[data-custom]').remove();recalculate()">Remove</button></article>`);recalculate()}
function customData(){return [...document.querySelectorAll('[data-custom]')].map(r=>({item_name:r.querySelector('[data-f=item_name]').value.trim(),quantity:Number(r.querySelector('[data-f=quantity]').value||1),item_price:Number(r.querySelector('[data-f=item_price]').value||0),thumbnail_path:r.querySelector('[data-f=thumbnail_path]').value,description:r.querySelector('[data-f=description]').value.trim()})).filter(x=>x.item_name||x.item_price)}
function total(){return [...SELECTED.values()].reduce((n,x)=>n+Number(tier(product(x.product_id),x.quantity)?.price||0),0)+customData().reduce((n,x)=>n+x.quantity*x.item_price,0)}
function recalculate(){const sum=total(),f=document.getElementById('comboForm');document.getElementById('comboSubtotal').textContent=money(sum);document.getElementById('comboSaving').textContent=`Customer saves ${money(Math.max(0,sum-Number(f.combo_price.value||0)))}.`}
function priceFromDiscount(){if(syncing)return;syncing=true;const f=document.getElementById('comboForm');f.combo_price.value=(total()*(1-Math.min(100,Number(f.discount_percent.value||0))/100)).toFixed(2);syncing=false;recalculate()}
function discountFromPrice(){if(syncing)return;syncing=true;const f=document.getElementById('comboForm'),sum=total();f.discount_percent.value=sum?Math.max(0,(1-Number(f.combo_price.value||0)/sum)*100).toFixed(2):0;syncing=false;recalculate()}
async function upload(file){const fd=new FormData();fd.append('image',file);return fetch('/admin/api/combo-offers/upload',{method:'POST',headers:{'X-CSRF-TOKEN':CSRF},body:fd}).then(r=>r.json())}
async function uploadCustom(input){if(!input.files[0])return;input.disabled=true;const r=await upload(input.files[0]);input.disabled=false;if(!r.ok)return alert(r.msg);const row=input.closest('[data-custom]');row.querySelector('[data-f=thumbnail_path]').value=r.path;row.querySelector('img').src=r.path}
async function init(){const r=await fetch('/admin/api/combo-offers').then(x=>x.json());PRODUCTS=r.products||[];CATEGORIES=r.categories||[];const occupied=new Map((r.offers||[]).filter(o=>Number(o.is_active)&&Number(o.id)!==EDIT_ID).map(o=>[o.layout_slot,o.title]));const updatePositionHelp=()=>{const slot=document.getElementById('layoutSlot').value,name=occupied.get(slot),help=document.getElementById('positionHelp');help.textContent=name?`Currently occupied by “${name}”. Choose another position or deactivate that offer first.`:'This position is available.';help.classList.toggle('is-warning',!!name)};document.getElementById('layoutSlot').addEventListener('change',updatePositionHelp);document.getElementById('categoryFilter').innerHTML='<option value="">Select Product Category</option>'+CATEGORIES.map(c=>`<option value="${Number(c.id)}">${esc(c.name)}</option>`).join('');if(EDIT_ID){const x=await fetch(`/admin/api/combo-offers/${EDIT_ID}`).then(v=>v.json()),o=x.offer,f=document.getElementById('comboForm');for(const[k,v]of Object.entries(o||{}))if(f.elements[k]&&f.elements[k].type!=='checkbox')f.elements[k].value=v??'';['show_title_home','show_title_detail','show_badge_home','show_badge_detail','show_cta_home','show_cta_detail','show_short_description_home','show_short_description_detail','show_description_home','show_description_detail'].forEach(k=>f.elements[k].checked=Number(o[k]??1)===1);(o.items||[]).forEach(v=>SELECTED.set(Number(v.product_id),{product_id:Number(v.product_id),quantity:Number(v.quantity)}));(o.custom_items||[]).forEach(addCustomItem);if(o.banner_image){document.getElementById('bannerPreview').src=o.banner_image;document.getElementById('bannerPreview').hidden=false}}updatePositionHelp();renderSelected();renderAvailable()}
document.getElementById('categoryFilter').addEventListener('change',renderAvailable);document.querySelector('[name=title]').addEventListener('input',e=>{if(!slugManual)document.querySelector('[name=slug]').value=slugify(e.target.value)});document.querySelector('[name=slug]').addEventListener('input',()=>slugManual=true);document.getElementById('bannerFile').addEventListener('change',async e=>{if(!e.target.files[0])return;const st=document.getElementById('uploadStatus');st.textContent='Uploading…';const r=await upload(e.target.files[0]);if(!r.ok){st.textContent=r.msg;return}document.querySelector('[name=banner_image]').value=r.path;document.getElementById('bannerPreview').src=r.path;document.getElementById('bannerPreview').hidden=false;st.textContent='Uploaded successfully.'});
document.getElementById('comboForm').addEventListener('submit',async e=>{e.preventDefault();const f=e.currentTarget,d=Object.fromEntries(new FormData(f).entries());d.products=[...SELECTED.values()];d.custom_items=customData();['show_title_home','show_title_detail','show_badge_home','show_badge_detail','show_cta_home','show_cta_detail','show_short_description_home','show_short_description_detail','show_description_home','show_description_detail'].forEach(k=>d[k]=f.elements[k].checked?1:0);const b=document.getElementById('saveButton');b.disabled=true;const r=await fetch(EDIT_ID?`/admin/api/combo-offers/${EDIT_ID}`:'/admin/api/combo-offers',{method:EDIT_ID?'PUT':'POST',headers:{'Content-Type':'application/json','X-CSRF-TOKEN':CSRF},body:JSON.stringify(d)}).then(x=>x.json());b.disabled=false;if(!r.ok){document.getElementById('formError').textContent=r.msg||'Save failed';return}location.href='/admin/combo-offers'});init();
</script></div></div></div></body></html>
