<?php $pageTitle='Combo Offers — RCS Admin';$currentAdmPage='combo-offers';include __DIR__.'/layout.php'; ?>
<div class="adm-pt">Combo Offers Manager</div>
<div class="fsec combo-admin">
  <div class="combo-admin-head"><p>Create product bundles with live quantity-tier pricing and optional custom items.</p><button class="btn btn-blue" type="button" onclick="openComboForm()">+ New Combo Offer</button></div>
  <div id="comboAdminList"></div>
</div>
<div class="adm-dialog" id="comboFormModal" hidden aria-hidden="true"><div class="adm-dialog-backdrop" onclick="closeComboForm()"></div><section class="adm-dialog-panel combo-admin-dialog" role="dialog" aria-modal="true" aria-labelledby="comboFormTitle"><button class="custom-quote-close" type="button" onclick="closeComboForm()">×</button><h2 id="comboFormTitle">New Combo Offer</h2>
<form id="comboForm" onsubmit="saveCombo(event)">
  <input type="hidden" name="id"><input type="hidden" name="regular_price">
  <div class="combo-form-grid"><label>Title<input class="fi" name="title" required></label><label>Slug<input class="fi" name="slug" placeholder="Generated from title if blank"></label></div>

  <fieldset class="combo-builder-section"><legend>Available Products</legend><p class="combo-help">Select products and their configured quantity. Prices come directly from product quantity pricing.</p><div id="comboProducts" class="combo-product-picker"></div></fieldset>

  <fieldset class="combo-builder-section"><legend>Custom Items</legend><div class="combo-admin-head"><p>Add items which are not available in the product catalog.</p><button type="button" class="btn btn-outline btn-sm" onclick="addCustomItem()">+ Add Custom Item</button></div><div id="comboCustomItems"></div></fieldset>

  <section class="combo-price-builder" aria-live="polite"><div><span>Products &amp; items subtotal</span><strong id="comboSubtotal">₹0</strong></div><div class="combo-form-grid"><label>Discount %<input class="fi" type="number" min="0" max="100" step="0.01" name="discount_percent" value="0" oninput="priceFromDiscount()"></label><label>Offer Price<input class="fi" type="number" min="0.01" step="0.01" name="combo_price" required oninput="discountFromPrice()"></label></div><small id="comboSaving">Final customer payable amount will be calculated here.</small></section>

  <div class="combo-form-grid"><label>Badge<input class="fi" name="badge" placeholder="Business starter pack"></label><label>Layout<select class="fi" name="layout_slot"><option value="large">Large</option><option value="wide">Wide</option><option value="square">Square</option></select></label><label>CTA Text<input class="fi" name="cta_text" value="View Offer"></label><label>Sort Order<input class="fi" type="number" name="sort_order" value="0"></label></div>
  <label>Short Description<textarea class="fi" name="short_description" rows="2"></textarea></label><label>Long Description<textarea class="fi" name="description" rows="4"></textarea></label>
  <label>Banner Image<input type="hidden" name="banner_image" id="comboBanner"><div class="combo-auto-upload"><input type="file" id="comboFile" accept="image/jpeg,image/png,image/webp" onchange="uploadComboImage(this)"><span id="comboUploadStatus">Select an image — it uploads automatically.</span><img id="comboBannerPreview" alt="Banner preview" hidden></div></label>
  <div class="combo-check-row"><label><input type="checkbox" name="show_on_home" checked> Show on homepage</label><label><input type="checkbox" name="is_active" checked> Active</label></div>
  <div class="adm-dialog-actions"><button type="button" class="btn btn-light" onclick="closeComboForm()">Cancel</button><button class="btn btn-blue" id="comboSaveBtn">Save Combo</button></div>
</form></section></div>
<script>
const COMBO_CSRF='<?= htmlspecialchars($csrf??'') ?>';let COMBOS=[],COMBO_PRODUCTS=[],customSequence=0,isPricingSync=false;
const ce=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const money=n=>'₹'+Number(n||0).toLocaleString('en-IN',{maximumFractionDigits:2});
async function loadCombos(){const r=await fetch('/admin/api/combo-offers').then(r=>r.json());if(!r.ok)return;COMBOS=r.offers||[];COMBO_PRODUCTS=r.products||[];document.getElementById('comboAdminList').innerHTML=COMBOS.length?COMBOS.map(o=>`<article class="combo-admin-row"><img src="${ce(o.banner_image||'')}" onerror="this.style.visibility='hidden'" alt=""><div><b>${ce(o.title)}</b><small>${ce(o.layout_slot)} · ${money(o.combo_price)} · ${Number(o.discount_percent||0).toFixed(2)}% off · ${Number(o.item_count)} items · ${Number(o.is_active)?'Active':'Inactive'}</small></div><div><a class="btn btn-outline btn-sm" href="/combo/${ce(o.slug)}" target="_blank">View</a><button class="btn btn-outline btn-sm" onclick="editCombo(${Number(o.id)})">Edit</button><button class="btn btn-outline btn-sm" onclick="deleteCombo(${Number(o.id)})">Delete</button></div></article>`).join(''):'<div class="adm-empty">No combo offers yet.</div>';}
function renderProducts(selected=[]){const chosen=new Map(selected.map(x=>[Number(x.product_id),x]));document.getElementById('comboProducts').innerHTML=COMBO_PRODUCTS.map(p=>{const saved=chosen.get(Number(p.id)),tiers=p.tiers||[],qty=Number(saved?.quantity||tiers[0]?.quantity||0),tier=tiers.find(t=>Number(t.quantity)===qty)||tiers[0],disabled=!tiers.length;return `<article class="combo-product-option ${saved?'is-selected':''}" data-product-id="${Number(p.id)}"><label class="combo-product-select"><input type="checkbox" ${saved?'checked':''} ${disabled?'disabled':''} onchange="toggleComboProduct(this)"><img src="${ce(p.thumbnail||'/assets/images/RCS%20PRINT%20LOGO.png')}" alt=""><strong>${ce(p.name)}</strong></label><select class="fi" ${saved?'':'disabled'} onchange="recalculateCombo()">${tiers.map(t=>`<option value="${Number(t.quantity)}" data-price="${Number(t.price)}" ${Number(t.quantity)===qty?'selected':''}>${Number(t.quantity).toLocaleString('en-IN')}</option>`).join('')}</select><b class="combo-line-price">${tier?money(tier.price):'Pricing unavailable'}</b></article>`}).join('');recalculateCombo();}
function toggleComboProduct(input){const row=input.closest('.combo-product-option');row.classList.toggle('is-selected',input.checked);row.querySelector('select').disabled=!input.checked;recalculateCombo();}
function addCustomItem(item={}){const id=++customSequence;document.getElementById('comboCustomItems').insertAdjacentHTML('beforeend',`<article class="combo-custom-row" data-custom-id="${id}"><div class="combo-custom-thumb"><img src="${ce(item.thumbnail_path||'/assets/images/RCS%20PRINT%20LOGO.png')}" alt=""><input type="hidden" data-custom-field="thumbnail_path" value="${ce(item.thumbnail_path||'')}"><input type="file" accept="image/jpeg,image/png,image/webp" onchange="uploadCustomImage(this)"></div><input class="fi" data-custom-field="item_name" value="${ce(item.item_name||'')}" placeholder="Item name" oninput="recalculateCombo()"><input class="fi" type="number" min="0.01" step="0.01" data-custom-field="item_price" value="${Number(item.item_price||'')||''}" placeholder="Price" oninput="recalculateCombo()"><button type="button" class="btn btn-outline btn-sm" onclick="this.closest('.combo-custom-row').remove();recalculateCombo()">Remove</button></article>`);recalculateCombo();}
function selectedProducts(){return [...document.querySelectorAll('.combo-product-option')].filter(r=>r.querySelector('input[type=checkbox]').checked).map(r=>({product_id:Number(r.dataset.productId),quantity:Number(r.querySelector('select').value),price:Number(r.querySelector('select').selectedOptions[0]?.dataset.price||0)}));}
function customItems(){return [...document.querySelectorAll('.combo-custom-row')].map(r=>({item_name:r.querySelector('[data-custom-field=item_name]').value.trim(),item_price:Number(r.querySelector('[data-custom-field=item_price]').value||0),thumbnail_path:r.querySelector('[data-custom-field=thumbnail_path]').value})).filter(x=>x.item_name||x.item_price);}
function subtotal(){return selectedProducts().reduce((n,x)=>n+x.price,0)+customItems().reduce((n,x)=>n+x.item_price,0);}
function recalculateCombo(){document.querySelectorAll('.combo-product-option').forEach(r=>{const o=r.querySelector('select').selectedOptions[0];r.querySelector('.combo-line-price').textContent=o?money(o.dataset.price):'Pricing unavailable'});const total=subtotal(),f=document.getElementById('comboForm');f.regular_price.value=total.toFixed(2);document.getElementById('comboSubtotal').textContent=money(total);if(!isPricingSync&&Number(f.combo_price.value)>total)f.combo_price.value=total?total.toFixed(2):'';updateSaving();}
function priceFromDiscount(){if(isPricingSync)return;isPricingSync=true;const f=document.getElementById('comboForm'),total=subtotal(),discount=Math.min(100,Math.max(0,Number(f.discount_percent.value||0)));f.combo_price.value=total?Math.max(0,total*(1-discount/100)).toFixed(2):'';isPricingSync=false;updateSaving();}
function discountFromPrice(){if(isPricingSync)return;isPricingSync=true;const f=document.getElementById('comboForm'),total=subtotal(),price=Number(f.combo_price.value||0);f.discount_percent.value=total?Math.max(0,Math.min(100,(1-price/total)*100)).toFixed(2):'0';isPricingSync=false;updateSaving();}
function updateSaving(){const f=document.getElementById('comboForm'),total=subtotal(),price=Number(f.combo_price.value||0);document.getElementById('comboSaving').textContent=total?`Customer pays ${money(price)} and saves ${money(Math.max(0,total-price))}.`:'Select products or add custom items to calculate the subtotal.';}
function openComboForm(){const f=document.getElementById('comboForm');f.reset();f.id.value='';f.cta_text.value='View Offer';f.show_on_home.checked=f.is_active.checked=true;document.getElementById('comboCustomItems').innerHTML='';document.getElementById('comboBannerPreview').hidden=true;document.getElementById('comboUploadStatus').textContent='Select an image — it uploads automatically.';renderProducts();document.getElementById('comboFormTitle').textContent='New Combo Offer';document.getElementById('comboFormModal').hidden=false;document.getElementById('comboFormModal').setAttribute('aria-hidden','false');}
function closeComboForm(){const m=document.getElementById('comboFormModal');m.hidden=true;m.setAttribute('aria-hidden','true');}
async function editCombo(id){const r=await fetch(`/admin/api/combo-offers/${id}`).then(r=>r.json());if(!r.ok)return;const f=document.getElementById('comboForm'),o=r.offer;f.reset();for(const [k,v] of Object.entries(o))if(f.elements[k]&&f.elements[k].type!=='checkbox')f.elements[k].value=v??'';f.id.value=o.id;f.show_on_home.checked=Number(o.show_on_home)===1;f.is_active.checked=Number(o.is_active)===1;document.getElementById('comboCustomItems').innerHTML='';(o.custom_items||[]).forEach(addCustomItem);renderProducts(o.items||[]);document.getElementById('comboBannerPreview').src=o.banner_image||'';document.getElementById('comboBannerPreview').hidden=!o.banner_image;document.getElementById('comboUploadStatus').textContent=o.banner_image?'Current banner loaded. Select a file to replace it.':'Select an image — it uploads automatically.';document.getElementById('comboFormTitle').textContent='Edit Combo Offer';const m=document.getElementById('comboFormModal');m.hidden=false;m.setAttribute('aria-hidden','false');updateSaving();}
async function saveCombo(e){e.preventDefault();const f=e.currentTarget,products=selectedProducts(),custom_items=customItems();if(!products.length&&!custom_items.length)return alert('Select at least one product or add a custom item.');const d=Object.fromEntries(new FormData(f).entries());d.products=products;d.custom_items=custom_items;d.show_on_home=f.show_on_home.checked?1:0;d.is_active=f.is_active.checked?1:0;const id=f.id.value,btn=document.getElementById('comboSaveBtn');btn.disabled=true;const r=await fetch(id?`/admin/api/combo-offers/${id}`:'/admin/api/combo-offers',{method:id?'PUT':'POST',headers:{'Content-Type':'application/json','X-CSRF-TOKEN':COMBO_CSRF},body:JSON.stringify(d)}).then(r=>r.json()).catch(()=>({ok:false,msg:'Could not save combo offer.'}));btn.disabled=false;if(!r.ok)return alert(r.msg||'Could not save');closeComboForm();loadCombos();}
async function uploadFile(file){const fd=new FormData();fd.append('image',file);return fetch('/admin/api/combo-offers/upload',{method:'POST',headers:{'X-CSRF-TOKEN':COMBO_CSRF},body:fd}).then(r=>r.json());}
async function uploadComboImage(input){const file=input.files[0];if(!file)return;const status=document.getElementById('comboUploadStatus');status.textContent='Uploading…';input.disabled=true;const r=await uploadFile(file).catch(()=>({ok:false,msg:'Upload failed.'}));input.disabled=false;if(!r.ok){status.textContent=r.msg||'Upload failed.';return;}document.getElementById('comboBanner').value=r.path;const preview=document.getElementById('comboBannerPreview');preview.src=r.path;preview.hidden=false;status.textContent='Uploaded successfully.';}
async function uploadCustomImage(input){const row=input.closest('.combo-custom-row'),img=row.querySelector('img');input.disabled=true;const r=await uploadFile(input.files[0]).catch(()=>({ok:false,msg:'Upload failed.'}));input.disabled=false;if(!r.ok)return alert(r.msg||'Upload failed.');row.querySelector('[data-custom-field=thumbnail_path]').value=r.path;img.src=r.path;}
async function deleteCombo(id){if(!await adminConfirm('Delete this combo offer?'))return;await fetch(`/admin/api/combo-offers/${id}`,{method:'DELETE',headers:{'X-CSRF-TOKEN':COMBO_CSRF}});loadCombos();}loadCombos();
</script></div></div></div></body></html>
