<?php $pageTitle='Combo Offers — RCS Admin';$currentAdmPage='combo-offers';include __DIR__.'/layout.php'; ?>
<div class="adm-page-head combo-list-head"><div><div class="adm-pt">Combo Offers Manager</div><p>Search, activate and manage promotional bundles.</p></div><form id="comboSearch" class="combo-search"><input class="fi" id="comboSearchInput" placeholder="Search Combo Offers"><button class="btn btn-outline" type="submit">Search</button><a class="btn btn-blue" href="/admin/combo-offers/new">+ Add New Combo Offer</a></form></div>
<div class="fsec combo-admin"><div id="comboAdminList"></div></div>
<script>
const CSRF='<?= htmlspecialchars($csrf??'') ?>',slotLabels={large:'Large Square — Left',wide:'Wide — Top Right',square_3:'Square — Bottom Right 1',square_4:'Square — Bottom Right 2'},esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m])),money=n=>'₹'+Number(n||0).toLocaleString('en-IN',{maximumFractionDigits:2});
async function loadCombos(){const q=document.getElementById('comboSearchInput').value.trim(),box=document.getElementById('comboAdminList');box.innerHTML='<div class="adm-empty">Loading…</div>';const r=await fetch('/admin/api/combo-offers?q='+encodeURIComponent(q)).then(x=>x.json()).catch(()=>({ok:false}));if(!r.ok){box.innerHTML='<div class="adm-empty">Could not load Combo Offers.</div>';return}const list=r.offers||[];box.innerHTML=list.length?list.map(o=>`<article class="combo-admin-row" data-combo-id="${Number(o.id)}"><img src="${esc(o.banner_image||'')}" alt=""><div><b>${esc(o.title)}</b><small>${esc(o.slug)} · ${money(o.combo_price)} · ${Number(o.item_count)} items<br><span class="combo-position-chip">${esc(slotLabels[o.layout_slot]||o.layout_slot)}</span></small></div><div><button class="combo-state-toggle ${Number(o.is_active)?'is-active':'is-inactive'}" onclick="toggleCombo(${Number(o.id)},this)">${Number(o.is_active)?'Active':'Inactive'}</button><a class="btn btn-outline btn-sm" href="/combo/${esc(o.slug)}" target="_blank">View</a><a class="btn btn-outline btn-sm" href="/admin/combo-offers/edit/${Number(o.id)}">Edit</a><button class="btn btn-outline btn-sm" onclick="deleteCombo(${Number(o.id)})">Delete</button></div></article>`).join(''):'<div class="adm-empty">No Combo Offers Found</div>';}
async function toggleCombo(id,button){button.disabled=true;const r=await fetch(`/admin/api/combo-offers/${id}/toggle`,{method:'POST',headers:{'X-CSRF-TOKEN':CSRF}}).then(x=>x.json()).catch(()=>({ok:false}));button.disabled=false;if(!r.ok)return alert(r.msg||'Status update failed');button.textContent=Number(r.is_active)?'Active':'Inactive';button.className='combo-state-toggle '+(Number(r.is_active)?'is-active':'is-inactive');}
async function deleteCombo(id){if(!await adminConfirm('Delete this combo offer?'))return;await fetch(`/admin/api/combo-offers/${id}`,{method:'DELETE',headers:{'X-CSRF-TOKEN':CSRF}});loadCombos();}
document.getElementById('comboSearch').addEventListener('submit',e=>{e.preventDefault();loadCombos()});loadCombos();
</script></div></div></div></body></html>
