<?php
$pageTitle = 'Custom Orders — RCS Admin';
$currentAdmPage = 'custom-orders';
$admMainClass = 'adm-main--orders';
include __DIR__ . '/layout.php';
?>
<div class="adm-orders-page custom-orders-page">
  <div class="custom-orders-toolbar"><button class="btn btn-blue btn-sm" type="button" onclick="openAdminQuoteModal()">＋ Add Custom Order</button><a href="/admin/export/custom-orders" class="btn btn-outline btn-sm adm-orders-export" target="_blank">⬇ Export CSV</a></div>
  <div id="customOrderStatusCards" class="custom-quote-status-grid"></div>
  <div id="customOrderList"><div style="text-align:center;padding:44px;color:var(--text2)"><div class="pay-spin" style="border-top-color:var(--blue);margin:0 auto 12px"></div>Loading custom orders…</div></div>
</div>
<div class="custom-quote-modal admin-custom-quote-modal" id="adminCustomQuoteModal" aria-hidden="true"><div class="custom-quote-backdrop" onclick="closeAdminQuoteModal()"></div><section class="custom-quote-dialog" role="dialog" aria-modal="true" aria-labelledby="adminCustomQuoteTitle"><button class="custom-quote-close" type="button" onclick="closeAdminQuoteModal()">×</button><header class="custom-quote-head"><div class="custom-quote-kicker">Admin Entry</div><h2 id="adminCustomQuoteTitle">Add <strong>Custom Order</strong></h2></header><form class="custom-quote-form" id="adminCustomQuoteForm" onsubmit="submitAdminCustomQuote(event)"><div class="custom-quote-grid"><label>Customer Name *<input name="customer_name" required></label><label>WhatsApp Number *<input name="phone" required></label><label>Email<input name="email" type="email"></label><label>Product Name *<input name="product_name" required></label><label>Size / Dimension<input name="size_dimension"></label><label>Material Type<input name="material_type"></label><label>Quantity<input name="quantity"></label></div><label>Instructions<textarea name="instructions" rows="3"></textarea></label><div class="custom-quote-message" id="adminCustomQuoteMessage"></div><button class="custom-quote-submit" type="submit">Add Custom Order</button></form></section></div>
<script>
const CSRF = '<?= htmlspecialchars($csrf??'') ?>';
let quotes=[],counts={},updateCounts={},activeFilter=(location.hash.replace('#','')||'new'),attentionFilter='';
const statuses=['new','reviewing','sent_to_customer','customer_approved','payment_pending','converted_to_order','rejected'];
const statusCards=[
  {key:'all',label:'All Quote',icon:'📋',tone:'all'}, {key:'new',label:'New Quote',icon:'🆕',tone:'new'},
  {key:'reviewing',label:'Reviewing',icon:'🔎',tone:'reviewing'}, {key:'sent_to_customer',label:'Send to Client',icon:'📨',tone:'sent'},
  {key:'customer_approved',label:'Approved',icon:'✅',tone:'approved'}, {key:'payment_pending',label:'Payment Pending',icon:'💳',tone:'payment'},
  {key:'converted_to_order',label:'Order Confirm',icon:'📦',tone:'confirmed'}, {key:'rejected',label:'Rejected',icon:'⛔',tone:'rejected'},
];
function esc(s){return String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));}
function attr(s){return esc(s).replace(/`/g,'&#96;');}
function statusLabel(s){return (statusCards.find(x=>x.key===s)?.label)||String(s||'new').replace(/_/g,' ').replace(/\b\w/g,c=>c.toUpperCase());}
function badgeForStatus(s){return ['customer_approved','paid','converted_to_order'].includes(s)?'b-green':(['rejected','closed'].includes(s)?'b-red':(['sent_to_customer','payment_pending','quoted'].includes(s)?'b-amber':'b-blue'));}
function waPhone(phone){let p=String(phone||'').replace(/\D+/g,'');if(p.length===10)p='91'+p;return p;}
function notify(msg,type='success'){const el=document.createElement('div');el.className=`custom-quote-toast custom-quote-toast--${type}`;el.textContent=msg;document.body.appendChild(el);setTimeout(()=>el.remove(),3200);}
async function loadCustomOrders(openId=0){const res=await fetch('/admin/api/custom-orders',{credentials:'same-origin'}).then(r=>r.json()).catch(()=>({ok:false,quotes:[],counts:{}}));quotes=res.quotes||[];counts=res.counts||{};updateCounts=res.update_counts||{};renderStatusCards();renderCustomOrders();if(openId){const card=document.getElementById(`cq-${openId}`);if(card)openCustomQuoteCard(card);}}
function renderStatusCards(){const box=document.getElementById('customOrderStatusCards');if(!box)return;box.innerHTML=statusCards.map(card=>{const attention=['new','converted_to_order'].includes(card.key)?Number(updateCounts[card.key]||0):0;return `<div class="custom-quote-status-wrap"><button type="button" class="custom-quote-status-card custom-quote-status-card--${card.tone} ${activeFilter===card.key&&!attentionFilter?'active':''}" onclick="setCustomQuoteFilter('${card.key}')"><span>${card.icon}</span><strong>${esc(card.label)}</strong><b>${Number(counts[card.key]||0).toLocaleString('en-IN')}</b></button>${attention?`<button type="button" class="custom-quote-update-count" aria-label="Show ${attention} unread ${esc(card.label)} updates" onclick="setCustomQuoteAttentionFilter('${card.key}')">(${attention})</button>`:''}</div>`;}).join('');}
function setCustomQuoteFilter(key){activeFilter=key;attentionFilter='';renderStatusCards();renderCustomOrders();}
function setCustomQuoteAttentionFilter(key){activeFilter=key;attentionFilter=key;renderStatusCards();renderCustomOrders();if(key==='converted_to_order'){const pending=quotes.filter(q=>['paid','converted_to_order'].includes(q.status)&&Number(q.customer_update_pending||0)===1);updateCounts[key]=0;renderStatusCards();pending.forEach(q=>fetch(`/admin/api/custom-orders/${Number(q.id)}/attention/clear`,{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-TOKEN':CSRF},credentials:'same-origin',body:'{}'}));}}
function filteredQuotes(){let list=activeFilter==='all'?quotes.filter(q=>!['rejected','closed'].includes(q.status||'new')):quotes.filter(q=>(q.status||'new')===activeFilter||(activeFilter==='converted_to_order'&&q.status==='paid'));if(attentionFilter==='new')list=list.filter(q=>Number(q.is_seen||0)===0);if(attentionFilter==='converted_to_order')list=list.filter(q=>Number(q.customer_update_pending||0)===1);return list;}
function detailValue(v,fallback='Not set'){return esc(v||fallback);}
function openAdminQuoteModal(){const m=document.getElementById('adminCustomQuoteModal');m.classList.add('open');m.setAttribute('aria-hidden','false');}
function closeAdminQuoteModal(){const m=document.getElementById('adminCustomQuoteModal');m.classList.remove('open');m.setAttribute('aria-hidden','true');}
async function submitAdminCustomQuote(e){e.preventDefault();const form=e.currentTarget,msg=document.getElementById('adminCustomQuoteMessage'),btn=e.submitter;btn.disabled=true;const res=await fetch('/admin/api/custom-orders',{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-TOKEN':CSRF},credentials:'same-origin',body:JSON.stringify(Object.fromEntries(new FormData(form).entries()))}).then(r=>r.json()).catch(()=>({ok:false,msg:'Could not add custom order'}));btn.disabled=false;if(!res.ok){msg.className='custom-quote-message error';msg.textContent=res.msg||'Could not add custom order';return;}form.reset();closeAdminQuoteModal();notify('Custom order added successfully.');await loadCustomOrders(res.id);}
function renderCustomOrders(){const box=document.getElementById('customOrderList'),list=filteredQuotes();if(!quotes.length){box.innerHTML='<div class="adm-empty">No custom quote requests yet.</div>';return;}if(!list.length){box.innerHTML='<div class="adm-empty">No quotes in this status.</div>';return;}box.innerHTML=`<div class="adm-order-card-list" aria-label="Custom quote requests list">${list.map(q=>{
 const id=Number(q.id||0),amount=Number(q.quoted_amount||0)+Number(q.design_fee||0),status=q.status||'new',pay=q.payment_status||'not_required',linked=Number(q.user_id||0)>0,canPay=linked&&status==='customer_approved';
 return `<article class="adm-order-card custom-quote-card custom-quote-card--${esc(status)}" id="cq-${id}" data-order-card data-quote-id="${id}">
 <div class="adm-order-card-head"><button class="adm-order-card-summary" type="button" aria-expanded="false" data-order-toggle onclick="toggleCustomQuoteCard(this)"><span class="adm-order-card-id"><strong>${esc(q.request_code||'#')}</strong><small>${esc(q.created_at||'')} · ${linked?'registered':'guest'}</small></span><span class="adm-order-card-customer"><strong>${esc(q.customer_name)}</strong><small>${esc(q.phone)}${q.email?' · '+esc(q.email):''}</small></span><span class="adm-order-card-meta"><b>₹${amount>0?amount.toLocaleString('en-IN'):'—'}</b><small>${esc(q.product_name||'Custom product')}</small></span><span class="adm-order-card-badges"><span class="badge ${badgeForStatus(status)}">${statusLabel(status)}</span>${pay!==status?`<span class="badge ${pay==='paid'?'b-green':(pay==='payment_pending'?'b-amber':'b-blue')}">${statusLabel(pay)}</span>`:''}${linked?'<span class="badge b-green">Account Linked</span>':'<span class="badge b-amber">Guest</span>'}</span></button><div class="adm-order-card-quick"><select class="fi fi-sel" aria-label="Select custom quote status" data-status-select>${statuses.map(s=>`<option value="${s}" ${s===status?'selected':''}>${statusLabel(s)}</option>`).join('')}</select><button class="btn btn-blue btn-sm" type="button" onclick="updateSelectedStatus(${id},this)">Update Status</button></div><button class="adm-order-card-toggle" type="button" aria-label="Expand custom quote ${esc(q.request_code||'')}" aria-expanded="false" data-order-toggle onclick="toggleCustomQuoteCard(this)">⌄</button></div>
 <div class="adm-order-card-body" hidden><div class="adm-order-card-grid"><section class="adm-order-card-section adm-order-card-section--full"><h3>Quote Details</h3><form class="custom-quote-edit" onsubmit="saveCustomQuote(event,${id})"><input type="hidden" name="customer_name" value="${attr(q.customer_name)}"><input type="hidden" name="phone" value="${attr(q.phone)}"><input type="hidden" name="email" value="${attr(q.email)}"><input type="hidden" name="payment_status" value="${attr(pay)}"><input type="hidden" name="status" value="${attr(status)}"><div class="custom-quote-detail-strip custom-quote-detail-strip--with-price"><label><span>Product</span><input class="fi" name="product_name" value="${attr(q.product_name)}" required></label><label><span>Size / Dimension</span><input class="fi" name="size_dimension" value="${attr(q.size_dimension)}"></label><label><span>Material</span><input class="fi" name="material_type" value="${attr(q.material_type)}"></label><label><span>Quantity</span><input class="fi" name="quantity" value="${attr(q.quantity)}"></label><label><span>Amount</span><input class="fi" type="number" step="0.01" min="0" name="quoted_amount" value="${attr(q.quoted_amount)}" placeholder="Enter price"></label><label><span>Design Fee</span><input class="fi" type="number" step="0.01" min="0" name="design_fee" value="${attr(q.design_fee||0)}" placeholder="0"></label></div><div class="custom-quote-instruction"><span>Customer Instructions</span><p>${esc(q.instructions||'No customer instructions provided.')}</p><input type="hidden" name="instructions" value="${attr(q.instructions)}"></div><label>Admin Quote Note / WhatsApp Details<textarea class="fi" name="quote_note" placeholder="Add final custom order details, terms and approval note for customer...">${esc(q.quote_note)}</textarea></label><div class="adm-order-action-strip custom-quote-actions"><div class="ord-action-strip-copy"><span class="ord-action-strip-label">Recommended flow</span><small>Save quote → WhatsApp quote → mark approved → create account → payment link.</small></div><div class="ord-actions ord-actions--compact"><button class="aoc-btn aoc-btn--invoice-upload" type="submit"><span class="aoc-ico">💾</span><span>Save Quote</span></button><button class="aoc-btn aoc-btn--wa" type="button" onclick="sendQuoteWhatsApp(${id})"><span class="aoc-ico">💬</span><span>WhatsApp Quote</span></button><button class="aoc-btn aoc-btn--confirm" type="button" onclick="markApproved(${id})"><span class="aoc-ico">✅</span><span>Mark Approved</span></button><button class="aoc-btn aoc-btn--address" type="button" onclick="createCustomerAccount(${id})"><span class="aoc-ico">👤</span><span>${linked?'Linked Account':'Create Account'}</span></button><button class="aoc-btn aoc-btn--invoice" type="button" onclick="generatePaymentLink(${id})"><span class="aoc-ico">🔗</span><span>Payment Link</span></button></div></div></form></section></div></div></article>`;}).join('')}</div>`;}
function openCustomQuoteCard(card){const body=card.querySelector('.adm-order-card-body');if(!body)return;body.hidden=false;card.classList.add('open');card.querySelectorAll('[data-order-toggle]').forEach(t=>t.setAttribute('aria-expanded','true'));}
function toggleCustomQuoteCard(btn){const card=btn.closest('[data-order-card]'),body=card?.querySelector('.adm-order-card-body');if(!card||!body)return;const open=body.hidden;body.hidden=!open;card.classList.toggle('open',open);card.querySelectorAll('[data-order-toggle]').forEach(t=>t.setAttribute('aria-expanded',open?'true':'false'));}
function formPayload(form){return Object.fromEntries(new FormData(form).entries());}
async function saveCustomQuote(e,id){e.preventDefault();const btn=e.submitter;btn&&(btn.disabled=true);const res=await fetch(`/admin/api/custom-orders/${id}`,{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-TOKEN':CSRF},credentials:'same-origin',body:JSON.stringify(formPayload(e.currentTarget))}).then(r=>r.json()).catch(()=>({ok:false,msg:'Could not save custom order'}));btn&&(btn.disabled=false);if(!res.ok){notify(res.msg||'Could not save custom order','error');return;}notify('Quote saved successfully.');await loadCustomOrders(id);}
async function updateSelectedStatus(id,btn){const status=btn.closest('.adm-order-card-quick').querySelector('[data-status-select]').value;await quickStatus(id,status);}
async function quickStatus(id,status){const res=await fetch(`/admin/api/custom-orders/${id}/status`,{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-TOKEN':CSRF},credentials:'same-origin',body:JSON.stringify({status})}).then(r=>r.json()).catch(()=>({ok:false,msg:'Could not update status'}));if(!res.ok){notify(res.msg||'Could not update status','error');return;}notify('Custom order status updated.');await loadCustomOrders(id);}
async function quoteMessage(id,type){const res=await fetch(`/admin/api/custom-orders/${id}/whatsapp-message`,{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-TOKEN':CSRF},credentials:'same-origin',body:JSON.stringify({type})}).then(r=>r.json()).catch(()=>({ok:false,msg:'Could not prepare WhatsApp message'}));return res;}
async function sendQuoteWhatsApp(id){const q=quotes.find(x=>Number(x.id)===id);if(!q)return;const res=await quoteMessage(id,'quote');if(!res.ok){notify(res.msg||'Please save the quote first.','error');return;}window.open(`https://wa.me/${waPhone(q.phone)}?text=${encodeURIComponent(res.message)}`,'_blank');await quickStatus(id,'sent_to_customer');}
async function markApproved(id){await quickStatus(id,'customer_approved');}
async function createCustomerAccount(id){const res=await fetch(`/admin/api/custom-orders/${id}/customer-account`,{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-TOKEN':CSRF},credentials:'same-origin',body:JSON.stringify({})}).then(r=>r.json()).catch(()=>({ok:false,msg:'Could not create/link account'}));if(!res.ok){notify(res.msg||'Could not create/link account','error');return;}notify(res.created?'Customer account created and custom order added to cart.':'Existing customer account linked and cart updated.');await loadCustomOrders(id);}
async function generatePaymentLink(id){const q=quotes.find(x=>Number(x.id)===id);if(!q)return;const res=await fetch(`/admin/api/custom-orders/${id}/payment-link`,{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-TOKEN':CSRF},credentials:'same-origin',body:JSON.stringify({})}).then(r=>r.json()).catch(()=>({ok:false,msg:'Could not generate payment link'}));if(!res.ok){notify(res.msg||'Could not generate payment link','error');return;}const msg=await quoteMessage(id,'payment');if(!msg.ok){notify(msg.msg||'Payment link generated, but message could not be prepared.','error');return;}window.open(`https://wa.me/${waPhone(q.phone)}?text=${encodeURIComponent(msg.message)}`,'_blank');notify('Payment link created. WhatsApp is ready to send.');await loadCustomOrders(id);}
window.adminAutoRefresh=()=>loadCustomOrders();
loadCustomOrders();
</script>
    </div></div></div>
</body></html>
