<?php $pageTitle='Header & Footer — RCS Admin';$currentAdmPage='header-footer';include __DIR__.'/layout.php'; ?>
<div class="adm-page-head"><div><div class="adm-pt">Header &amp; Footer CMS</div><p>Choose a section, edit only what you need, then publish it across the website.</p></div><button class="btn btn-blue" type="button" id="saveChrome">Save Changes</button></div>
<div class="chrome-cms" id="chromeCms">
  <aside class="chrome-cms-nav" aria-label="Header and footer sections">
    <strong>Header</strong><button class="is-active" data-section="announcement">Announcement Bar</button><button data-section="branding">Logo &amp; CTA</button><button data-section="header_menu">Main Menu</button>
    <strong>Footer</strong><button data-section="footer_content">Content &amp; Logo</button><button data-section="footer_menus">Footer Menus</button><button data-section="contact">Contact &amp; Newsletter</button><button data-section="social">Social &amp; Copyright</button>
  </aside>
  <form id="chromeForm" class="chrome-cms-workspace">
    <section class="chrome-cms-section is-active" data-panel="announcement"><h2>Announcement Bar</h2><p>Manage the promotional message shown above the public header.</p><div class="combo-form-grid"><label>Announcement text<input class="fi" name="top_bar_text"></label><label>Optional link<input class="fi" name="top_bar_url" placeholder="/offer or https://..."></label></div><label class="chrome-switch"><input type="checkbox" name="top_bar_active"> Display announcement bar</label></section>
    <section class="chrome-cms-section" data-panel="branding"><h2>Header Branding &amp; CTA</h2><div class="combo-form-grid"><label>Header logo<input class="fi" name="header_logo" required><span class="chrome-one-click"><input type="file" data-logo="header_logo" accept="image/png,image/jpeg,image/webp">Select a new logo to upload instantly</span></label><label>Quote button text<input class="fi" name="header_quote_text" maxlength="80"></label></div></section>
    <section class="chrome-cms-section" data-panel="header_menu"><div class="combo-admin-head"><div><h2>Main Menu</h2><p>Use <code>@products</code> as the URL to keep the dynamic Products dropdown.</p></div><button class="btn btn-outline btn-sm" type="button" onclick="addNav('header')">+ Add Menu Item</button></div><div data-nav="header"></div></section>
    <section class="chrome-cms-section" data-panel="footer_content"><h2>Footer Content</h2><div class="combo-form-grid"><label>Footer logo<input class="fi" name="footer_logo" required><span class="chrome-one-click"><input type="file" data-logo="footer_logo" accept="image/png,image/jpeg,image/webp">Select a new logo to upload instantly</span></label><label>Footer description<textarea class="fi" name="footer_description" rows="5"></textarea></label></div></section>
    <section class="chrome-cms-section" data-panel="footer_menus"><h2>Footer Menus</h2><div id="footerMenuEditors" class="chrome-nav-grid"></div></section>
    <section class="chrome-cms-section" data-panel="contact"><h2>Contact &amp; Newsletter</h2><p>Phone, email and address continue to use Business Settings.</p><div class="combo-form-grid"><label>Contact heading<input class="fi" name="footer_contact_heading"></label><label>Business hours<input class="fi" name="footer_hours"></label><label>Newsletter heading<input class="fi" name="footer_newsletter_heading"></label><label>Newsletter text<textarea class="fi" name="footer_newsletter_text" rows="3"></textarea></label></div></section>
    <section class="chrome-cms-section" data-panel="social"><h2>Social Links &amp; Footer Bottom</h2><div class="combo-form-grid"><label>Facebook URL<input class="fi" name="social_facebook"></label><label>Instagram URL<input class="fi" name="social_instagram"></label><label>LinkedIn URL<input class="fi" name="social_linkedin"></label><label>YouTube URL<input class="fi" name="social_youtube"></label><label>Copyright text<input class="fi" name="footer_copyright"><small>Available tokens: {year}, {business}</small></label><label>Developer credit<input class="fi" name="footer_developer"></label></div></section>
    <div class="chrome-save-state" id="chromeSaveState" role="status"></div>
  </form>
</div>
<script>
const CHROME_CSRF='<?= htmlspecialchars($csrf??'',ENT_QUOTES) ?>',locations={header:'Main Menu',footer_quick:'Quick Links',footer_products:'Products',footer_service:'Customer Service'};let chromeData={settings:{},navigation:{}};
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function navRow(x={},key=''){return `<div class="chrome-nav-row"><span class="chrome-drag" title="Use arrows to reorder">⋮⋮</span><input class="fi" data-field="label" value="${esc(x.label)}" placeholder="Menu text"><input class="fi" data-field="url" value="${esc(x.url)}" placeholder="/page-link"><label class="chrome-nav-active"><input type="checkbox" data-field="is_active" ${Number(x.is_active??1)?'checked':''}> Active</label><span class="chrome-order-actions"><button type="button" onclick="moveNav(this,-1)" aria-label="Move up">↑</button><button type="button" onclick="moveNav(this,1)" aria-label="Move down">↓</button></span><button type="button" class="btn btn-outline btn-sm" onclick="removeNav(this)">Remove</button></div>`;}
function renderEditors(){document.querySelector('[data-nav="header"]').innerHTML=(chromeData.navigation.header||[]).map(x=>navRow(x,'header')).join('');document.getElementById('footerMenuEditors').innerHTML=Object.entries(locations).filter(([key])=>key!=='header').map(([key,title])=>`<section class="chrome-nav-editor"><div class="combo-admin-head"><h3>${title}</h3><button type="button" class="btn btn-outline btn-sm" onclick="addNav('${key}')">+ Add Link</button></div><div data-nav="${key}">${(chromeData.navigation[key]||[]).map(x=>navRow(x,key)).join('')}</div></section>`).join('');}
function addNav(key){document.querySelector(`[data-nav="${key}"]`).insertAdjacentHTML('beforeend',navRow({},key));}
async function removeNav(button){if(await adminConfirm('Remove this menu item?'))button.closest('.chrome-nav-row').remove();}
function moveNav(button,direction){const row=button.closest('.chrome-nav-row'),sibling=direction<0?row.previousElementSibling:row.nextElementSibling;if(!sibling)return;direction<0?row.parentElement.insertBefore(row,sibling):row.parentElement.insertBefore(sibling,row);}
async function uploadLogo(key,file){if(!file)return;const state=document.getElementById('chromeSaveState');state.textContent='Uploading image…';const fd=new FormData();fd.append('image',file);const r=await fetch('/admin/api/site-chrome/logo',{method:'POST',headers:{'X-CSRF-TOKEN':CHROME_CSRF},body:fd}).then(x=>x.json()).catch(()=>({ok:false,msg:'Upload failed'}));if(r.ok){document.getElementById('chromeForm').elements[key].value=r.path;state.textContent='Image uploaded. Save changes to publish it.';}else state.textContent=r.msg||'Upload failed.';}
async function loadChrome(){const r=await fetch('/admin/api/site-chrome',{cache:'no-store'}).then(x=>x.json());if(!r.ok)return;chromeData=r.data;const f=document.getElementById('chromeForm');for(const[k,v]of Object.entries(chromeData.settings)){if(!f.elements[k])continue;if(f.elements[k].type==='checkbox')f.elements[k].checked=Number(v)===1;else f.elements[k].value=v||'';}renderEditors();}
function collect(){const f=document.getElementById('chromeForm'),settings={};for(const field of f.querySelectorAll('[name]'))settings[field.name]=field.type==='checkbox'?(field.checked?1:0):field.value;const navigation={};for(const key of Object.keys(locations))navigation[key]=[...document.querySelectorAll(`[data-nav="${key}"] .chrome-nav-row`)].map(row=>({label:row.querySelector('[data-field="label"]').value.trim(),url:row.querySelector('[data-field="url"]').value.trim(),is_active:row.querySelector('[data-field="is_active"]').checked?1:0}));return{settings,navigation};}
async function saveChrome(){const button=document.getElementById('saveChrome'),state=document.getElementById('chromeSaveState');button.disabled=true;state.textContent='Saving…';const r=await fetch('/admin/api/site-chrome',{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-TOKEN':CHROME_CSRF},body:JSON.stringify(collect())}).then(x=>x.json()).catch(()=>({ok:false,msg:'Save failed'}));button.disabled=false;state.textContent=r.ok?'Header and footer published successfully.':(r.msg||'Save failed.');}
document.querySelectorAll('.chrome-cms-nav button').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('.chrome-cms-nav button,.chrome-cms-section').forEach(el=>el.classList.remove('is-active'));button.classList.add('is-active');document.querySelector(`[data-panel="${button.dataset.section}"]`).classList.add('is-active');}));
document.querySelectorAll('[data-logo]').forEach(input=>input.addEventListener('change',()=>uploadLogo(input.dataset.logo,input.files[0])));document.getElementById('saveChrome').addEventListener('click',saveChrome);loadChrome();
</script></div></div></div></body></html>
