<?php $pageTitle='Add Order — RCS Admin';$currentAdmPage='orders';include __DIR__.'/layout.php';$h=static fn($v)=>htmlspecialchars((string)$v,ENT_QUOTES); ?>
<main class="adm-create-order-page"><header class="adm-page-head"><div><a href="/admin/orders">← All Orders</a><h1>Add Order</h1><p>Create a secure pending-payment order on behalf of a customer.</p></div></header>
<form id="adminOrderForm" class="adm-order-wizard">
 <section class="fsec"><div class="adm-step-title"><b>1</b><div><h2>Customer</h2><p>Select an existing account or create one with the mobile number as the initial password.</p></div></div><label>Existing customer<select class="fi" name="user_id" id="aoUser"><option value="">Create a new customer</option><?php foreach($customers as $customer): ?><option value="<?= (int)$customer['id'] ?>"><?= $h($customer['name'].' · '.$customer['email'].' · '.$customer['phone']) ?></option><?php endforeach; ?></select></label><div class="combo-form-grid" id="aoNewCustomer"><label>Customer name<input class="fi" name="customer_name"></label><label>Email<input class="fi" type="email" name="customer_email"></label><label>Mobile number<input class="fi" name="customer_phone" inputmode="tel"></label></div></section>
 <section class="fsec"><div class="adm-step-title"><b>2</b><div><h2>Product &amp; Design</h2><p>Pricing is taken from the selected product’s configured quantity tier.</p></div></div><label>Product<select class="fi" name="product_id" id="aoProduct" required><option value="">Select product</option><?php foreach($products as $product): $tiers=array_values($product['quantity_tiers']??[]); ?><option value="<?= (int)$product['id'] ?>" data-tiers='<?= $h(json_encode($tiers)) ?>'><?= $h($product['name']) ?></option><?php endforeach; ?></select></label><div class="combo-form-grid"><label>Quantity<select class="fi" name="quantity" id="aoQuantity" required><option value="">Select product first</option></select></label><label>Design option<select class="fi" name="design_choice"><option value="upload">Customer will upload design</option><option value="rcs">RCS will create design</option></select></label></div><label>Design brief<textarea class="fi" name="design_brief" rows="3"></textarea></label><label>Admin/order note<textarea class="fi" name="notes" rows="3"></textarea></label></section>
 <section class="fsec"><div class="adm-step-title"><b>3</b><div><h2>Payment &amp; Creation</h2><p>Payment remains Pending Payment until Razorpay verifies the customer’s payment.</p></div></div><div class="adm-pending-payment-note">🔒 This action never marks an order paid. The customer pays securely from My Account.</div><button class="btn btn-blue" id="aoSubmit" type="submit">Create Pending Order</button><div id="aoState" role="status"></div></section>
</form><section id="aoResult" class="adm-order-created" hidden></section></main>
<script>
const AO_CSRF='<?= $h($csrf??'') ?>',aoForm=document.getElementById('adminOrderForm'),aoUser=document.getElementById('aoUser'),aoProduct=document.getElementById('aoProduct'),aoQty=document.getElementById('aoQuantity');
const aoEsc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
aoUser.addEventListener('change',()=>document.getElementById('aoNewCustomer').hidden=Boolean(aoUser.value));
aoProduct.addEventListener('change',()=>{let tiers=[];try{tiers=JSON.parse(aoProduct.selectedOptions[0]?.dataset.tiers||'[]')}catch(e){}aoQty.innerHTML=tiers.length?tiers.map(t=>`<option value="${Number(t.quantity)}">${Number(t.quantity).toLocaleString('en-IN')} units — ₹${Number(t.price).toLocaleString('en-IN')}</option>`).join(''):'<option value="">No pricing tiers configured</option>';});
aoForm.addEventListener('submit',async e=>{e.preventDefault();const button=document.getElementById('aoSubmit'),state=document.getElementById('aoState');button.disabled=true;state.textContent='Creating customer and order…';const payload=Object.fromEntries(new FormData(aoForm));try{const response=await fetch('/admin/api/orders/create',{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-TOKEN':AO_CSRF},credentials:'same-origin',body:JSON.stringify(payload)}),data=await response.json();if(!response.ok||!data.ok)throw new Error(data.msg||'Creation failed');const order=data.order||{},phone=String(order.customer_phone||'').replace(/\D/g,''),login='<?= $h(rtrim(APP_URL,'/')) ?>/login',message=`Hello ${order.customer_name||'Customer'}, your order #${order.order_id} has been added by RCS Graphic. Login at ${login} and open My Orders to complete the pending payment.${data.temporary_password?` Your initial password is your mobile number: ${data.temporary_password}`:''}`;aoForm.hidden=true;const result=document.getElementById('aoResult');result.hidden=false;result.innerHTML=`<span class="badge b-purple">Order Added by Admin</span><h2>Order #${aoEsc(order.order_id)} created</h2><p><b>${aoEsc(order.customer_name)}</b> · ₹${Number(order.total_amount||0).toLocaleString('en-IN')} · <strong>Pending Payment</strong></p>${data.temporary_password?`<p>Account created. Initial password: <code>${aoEsc(data.temporary_password)}</code></p>`:''}<div><a class="btn btn-blue" href="/admin/orders?search=${encodeURIComponent(order.order_id)}">View Order</a><a class="btn btn-green" target="_blank" rel="noopener" href="https://wa.me/${encodeURIComponent(phone)}?text=${encodeURIComponent(message)}">WhatsApp Customer</a></div>`;}catch(error){state.textContent=error.message;}finally{button.disabled=false;}});
</script></div></div></div></body></html>
