<?php $pageTitle='Add Order — RCS Admin';$currentAdmPage='orders';include __DIR__.'/layout.php';$h=static fn($v)=>htmlspecialchars((string)$v,ENT_QUOTES);$adminOrderProducts=array_map(static fn($p)=>['id'=>(int)$p['id'],'category_id'=>(int)($p['category_id']??0),'name'=>(string)$p['name'],'design_fee'=>(float)($p['design_fee']??0),'tiers'=>array_map(static fn($t)=>['quantity'=>(int)$t['quantity'],'price'=>(float)$t['price']],$p['quantity_tiers']??[])],$products);$adminOrderCustomers=array_map(static fn($c)=>['id'=>(int)$c['id'],'name'=>(string)($c['name']??''),'email'=>(string)($c['email']??''),'phone'=>(string)($c['phone']??''),'company'=>(string)($c['company']??'')],$customers); ?>
<main class="adm-create-order-page"><header class="adm-page-head"><div><a href="/admin/orders">← All Orders</a><h1>Add Order</h1><p>Create a pending-payment order using the same product pricing and design choices customers use.</p></div></header>
<form id="adminOrderForm" class="adm-order-wizard">
 <section class="fsec"><div class="adm-step-title"><b>1</b><div><h2>Customer</h2><p>Select an existing account to load its saved details, or create a customer with the mobile number as the initial password.</p></div></div><label>Existing customer<select class="fi" name="user_id" id="aoUser"><option value="">Create a new customer</option><?php foreach($customers as $customer): ?><option value="<?= (int)$customer['id'] ?>"><?= $h($customer['name'].' · '.$customer['email'].' · '.$customer['phone']) ?></option><?php endforeach; ?></select></label><div class="adm-customer-loaded" id="aoCustomerState">Enter details for a new customer.</div><div class="combo-form-grid" id="aoCustomerFields"><label>Customer name<input class="fi" id="aoCustomerName" name="customer_name" required></label><label>Email<input class="fi" id="aoCustomerEmail" type="email" name="customer_email" required></label><label>Mobile number<input class="fi" id="aoCustomerPhone" name="customer_phone" inputmode="tel" required></label><label>Company<input class="fi" id="aoCustomerCompany" name="customer_company"></label></div></section>
 <section class="fsec"><div class="adm-step-title"><b>2</b><div><h2>Product &amp; Design</h2><p>Choose a category first; products and configured quantities are then filtered automatically.</p></div></div><label>Product category<select class="fi" name="category_id" id="aoCategory" required><option value="">Select Product Category</option><?php foreach($categories as $category): ?><option value="<?= (int)$category['id'] ?>"><?= $h($category['name']) ?></option><?php endforeach; ?></select></label><label>Product<select class="fi" name="product_id" id="aoProduct" required disabled><option value="">Select category first</option></select></label><div class="combo-form-grid"><label>Quantity &amp; price<select class="fi" name="quantity" id="aoQuantity" required disabled><option value="">Select product first</option></select></label></div>
  <fieldset class="adm-design-choice"><legend>Design option</legend><label><input type="radio" name="design_choice" value="upload" checked><span><i class="fa-solid fa-cloud-arrow-up"></i><strong>Upload Your Design</strong><small>Customer can upload the print-ready design now or later from My Account.</small></span></label><label><input type="radio" name="design_choice" value="rcs"><span><i class="fa-regular fa-pen-to-square"></i><strong>Design by RCS Graphic</strong><small>Our experts will prepare the artwork; the configured design fee is included.</small></span></label></fieldset>
  <label>Design brief<textarea class="fi" name="design_brief" rows="3"></textarea></label><label>Admin/order note<textarea class="fi" name="notes" rows="3"></textarea></label></section>
 <section class="fsec"><div class="adm-step-title"><b>3</b><div><h2>Review &amp; Create</h2><p id="aoPriceSummary">Select a category, product and quantity to review pricing.</p></div></div><div class="adm-pending-payment-note">🔒 Payment remains Pending Payment until Razorpay verifies the customer’s payment.</div><button class="btn btn-blue" id="aoSubmit" type="submit">Create Order</button><div id="aoState" role="status" aria-live="polite"></div></section>
</form><section id="aoResult" class="adm-order-created" hidden></section></main>
<script>
const AO_CSRF='<?= $h($csrf??'') ?>',AO_PRODUCTS=<?= json_encode($adminOrderProducts,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_HEX_TAG|JSON_HEX_AMP) ?>,AO_CUSTOMERS=<?= json_encode($adminOrderCustomers,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_HEX_TAG|JSON_HEX_AMP) ?>;
const aoForm=document.getElementById('adminOrderForm'),aoUser=document.getElementById('aoUser'),aoCategory=document.getElementById('aoCategory'),aoProduct=document.getElementById('aoProduct'),aoQty=document.getElementById('aoQuantity'),aoPrice=document.getElementById('aoPriceSummary');
const aoEsc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function selectedProduct(){return AO_PRODUCTS.find(p=>p.id===Number(aoProduct.value));}
function renderPrice(){const product=selectedProduct(),tier=product?.tiers.find(t=>t.quantity===Number(aoQty.value)),rcs=aoForm.elements.design_choice.value==='rcs';if(!tier){aoPrice.textContent='Select a configured quantity to review pricing.';return;}const fee=rcs?Number(product.design_fee||0):0;aoPrice.textContent=`${Number(tier.quantity).toLocaleString('en-IN')} units · Base ₹${Number(tier.price).toLocaleString('en-IN')}${fee?` + Design ₹${fee.toLocaleString('en-IN')}`:''}`;}
function loadCustomer(){const customer=AO_CUSTOMERS.find(item=>item.id===Number(aoUser.value))||null,fields={name:document.getElementById('aoCustomerName'),email:document.getElementById('aoCustomerEmail'),phone:document.getElementById('aoCustomerPhone'),company:document.getElementById('aoCustomerCompany')};fields.name.value=customer?.name||'';fields.email.value=customer?.email||'';fields.phone.value=customer?.phone||'';fields.company.value=customer?.company||'';Object.values(fields).forEach(field=>field.readOnly=Boolean(customer));document.getElementById('aoCustomerState').textContent=customer?`Loaded customer #${customer.id} from the customer database. These saved details will be used for the order.`:'Enter details for a new customer.';document.getElementById('aoCustomerFields').classList.toggle('is-loaded',Boolean(customer));}
aoUser.addEventListener('change',loadCustomer);loadCustomer();
aoCategory.addEventListener('change',()=>{const products=AO_PRODUCTS.filter(p=>p.category_id===Number(aoCategory.value));aoProduct.disabled=!products.length;aoProduct.innerHTML=products.length?'<option value="">Select Product</option>'+products.map(p=>`<option value="${p.id}">${aoEsc(p.name)}</option>`).join(''):'<option value="">No active products in this category</option>';aoQty.disabled=true;aoQty.innerHTML='<option value="">Select product first</option>';renderPrice();});
aoProduct.addEventListener('change',()=>{const tiers=selectedProduct()?.tiers||[];aoQty.disabled=!tiers.length;aoQty.innerHTML=tiers.length?'<option value="">Select Quantity</option>'+tiers.map(t=>`<option value="${t.quantity}">${Number(t.quantity).toLocaleString('en-IN')} units — ₹${Number(t.price).toLocaleString('en-IN')}</option>`).join(''):'<option value="">No pricing configured</option>';renderPrice();});aoQty.addEventListener('change',renderPrice);aoForm.querySelectorAll('[name="design_choice"]').forEach(input=>input.addEventListener('change',renderPrice));
aoForm.addEventListener('submit',async e=>{e.preventDefault();const button=document.getElementById('aoSubmit'),state=document.getElementById('aoState');button.disabled=true;state.textContent='Creating customer and order…';const payload=Object.fromEntries(new FormData(aoForm));try{const response=await fetch('/admin/api/orders/create',{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-TOKEN':AO_CSRF},credentials:'same-origin',body:JSON.stringify(payload)}),data=await response.json();if(!response.ok||!data.ok)throw new Error(data.msg||'Order could not be created.');const order=data.order||{},phone=String(order.customer_phone||'').replace(/\D/g,''),login='<?= $h(rtrim(APP_URL,'/')) ?>/login',message=`Hello ${order.customer_name||'Customer'}, your order ${order.order_id} has been added by RCS Graphic. Login at ${login} and open My Orders to complete the pending payment.${data.temporary_password?` Your initial password is your mobile number: ${data.temporary_password}`:''}`;aoForm.hidden=true;const result=document.getElementById('aoResult');result.hidden=false;result.innerHTML=`<span class="badge b-purple">Order Added by Admin</span><h2>Order ${aoEsc(order.order_id)} created</h2><p><b>${aoEsc(order.customer_name)}</b> · ₹${Number(order.total_amount||0).toLocaleString('en-IN')} · <strong>Pending Payment</strong></p>${data.temporary_password?`<p>Account created. Initial password: <code>${aoEsc(data.temporary_password)}</code></p>`:''}<div><a class="btn btn-blue" href="/admin/orders?search=${encodeURIComponent(order.order_id)}">View Order</a><a class="btn btn-green" target="_blank" rel="noopener" href="https://wa.me/${encodeURIComponent(phone)}?text=${encodeURIComponent(message)}">WhatsApp Customer</a></div>`;}catch(error){state.textContent=error.message;}finally{button.disabled=false;}});
</script></div></div></div></body></html>
