<?php $pageTitle='Add Filter Options — RCS Admin';$currentAdmPage='product-filters';include __DIR__.'/layout.php'; ?>
<div class="adm-page-head"><div><div class="adm-pt">Add Filter Options</div><p>Manage the database-driven filters shown on category listing pages.</p></div><a class="btn btn-outline" href="/admin/products">← Products</a></div>
<section class="fsec"><form id="filterForm" class="filter-admin-row"><label>Group Name<input class="fi" name="group_label" placeholder="e.g. Paper Type" required></label><label>Group Key<input class="fi" name="group_slug" placeholder="paper-type" required></label><label>Option Name<input class="fi" name="label" placeholder="e.g. Glossy Paper" required></label><label>Sort<input class="fi" name="sort_order" type="number" value="0"></label><button class="btn btn-blue" type="submit">Add Option</button></form></section>
<section class="fsec"><h2>Existing Filter Options</h2><div id="filterRows" class="filter-admin-grid"><div class="adm-empty">Loading…</div></div></section>
<script>
const FILTER_CSRF='<?= htmlspecialchars($csrf??'',ENT_QUOTES) ?>';
const filterEsc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
async function loadFilterOptions(){const data=await fetch('/admin/api/product-filter-options').then(r=>r.json());const box=document.getElementById('filterRows'),rows=data.options||[];box.innerHTML=rows.length?rows.map(row=>`<article class="filter-admin-row"><label>Group<input class="fi" value="${filterEsc(row.group_label)}" disabled></label><label>Key<input class="fi" value="${filterEsc(row.group_slug)}" disabled></label><label>Option<input class="fi" value="${filterEsc(row.label)}" disabled></label><label>Sort<input class="fi" value="${Number(row.sort_order||0)}" disabled></label><button class="btn btn-outline btn-sm" type="button" onclick="deleteFilterOption(${Number(row.id)})">Remove</button></article>`).join(''):'<div class="adm-empty">No filter options found.</div>';}
document.getElementById('filterForm').addEventListener('submit',async event=>{event.preventDefault();const form=event.currentTarget,payload=Object.fromEntries(new FormData(form).entries());const data=await fetch('/admin/api/product-filter-options',{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-TOKEN':FILTER_CSRF},body:JSON.stringify(payload)}).then(r=>r.json());if(!data.ok){alert(data.msg||'Could not add filter');return;}form.reset();await loadFilterOptions();});
async function deleteFilterOption(id){if(!confirm('Remove this filter option from products and category filters?'))return;const data=await fetch(`/admin/api/product-filter-options/${id}`,{method:'DELETE',headers:{'X-CSRF-TOKEN':FILTER_CSRF}}).then(r=>r.json());if(!data.ok){alert(data.msg||'Could not remove filter');return;}loadFilterOptions();}
loadFilterOptions();
</script></div></div></div></body></html>
