<?php $pageTitle='Revenue Report — RCS Admin';$currentAdmPage='dashboard';include __DIR__.'/layout.php';$h=static fn($v)=>htmlspecialchars((string)$v,ENT_QUOTES);$labels=['new_order'=>'New Order','received'=>'Received','design_approved'=>'Design Approved','printing'=>'Printing','other_process'=>'Other Process','processing'=>'Processing','ready'=>'Dispatched','delivered'=>'Delivered','cancelled'=>'Cancelled','whatsapp_pending'=>'WA Pending']; ?>
<main class="adm-report-page">
  <header class="adm-report-head"><div><a href="/admin/dashboard">← Dashboard</a><h1>Revenue &amp; Order Report</h1><p><?= $start ? $h($start->format('d M Y')).' – ' : 'All records through ' ?><?= $h($end->format('d M Y')) ?> · Revenue includes paid orders only.</p></div>
    <form method="get" action="/admin/reports/revenue" class="adm-report-filter"><input type="hidden" name="mode" value="range"><label>Start date<input class="fi" type="date" name="start" value="<?= $start?$h($start->format('Y-m-d')):'' ?>" required></label><label>End date<input class="fi" type="date" name="end" value="<?= $h($end->format('Y-m-d')) ?>" required></label><button class="btn btn-blue">Apply Range</button></form>
  </header>
  <?php if(!empty($reportError)): ?><div class="adm-report-error"><?= $h($reportError) ?></div><?php endif; ?>
  <section class="adm-report-kpis">
    <?php foreach([['Total Orders',$summary['total_orders']??0,'/admin/orders'],['Paid Orders',$summary['paid_orders']??0,'/admin/orders?payment_status=paid'],['Pending Payment',$summary['pending_orders']??0,'/admin/orders?payment_status=pending'],['Paid Revenue','₹'.number_format((float)($summary['revenue']??0),2),'#orders'],['Average Order Value','₹'.number_format((float)($summary['avg_order_value']??0),2),'#orders'],['Custom Orders',$summary['custom_orders']??0,'/admin/orders?search=custom']] as [$title,$value,$href]): ?><a href="<?= $h($href) ?>"><span><?= $h($title) ?></span><strong><?= $h($value) ?></strong></a><?php endforeach; ?>
  </section>
  <section class="adm-report-grid"><article class="adm-report-card"><div class="adm-report-card-head"><h2>Paid Revenue by Date</h2><small><?= count($daily) ?> active date(s)</small></div><div class="adm-report-bars"><?php $max=max(array_map(static fn($r)=>(float)$r['revenue'],$daily)?:[1]);foreach($daily as $row): ?><div><span><?= $h(date('d M',strtotime($row['report_date']))) ?></span><i><b style="width:<?= max(2,round(((float)$row['revenue']/max($max,1))*100)) ?>%"></b></i><strong>₹<?= number_format((float)$row['revenue']) ?></strong></div><?php endforeach; ?><?php if(!$daily): ?><p>No orders in this range.</p><?php endif; ?></div></article><article class="adm-report-card"><div class="adm-report-card-head"><h2>Orders by Status</h2></div><div class="adm-report-statuses"><?php foreach($statuses as $row): ?><a href="/admin/orders?status=<?= urlencode((string)$row['status']) ?>"><span><?= $h($labels[$row['status']]??ucwords(str_replace('_',' ',$row['status']))) ?></span><strong><?= number_format((int)$row['count']) ?></strong></a><?php endforeach; ?></div></article></section>
  <article class="adm-report-card" id="orders"><div class="adm-report-card-head"><div><h2>Orders in Selected Range</h2><small>Maximum 250 latest records</small></div><a href="/admin/orders">Open All Orders</a></div><div class="adm-report-table-wrap"><table><thead><tr><th>Order</th><th>Customer</th><th>Product</th><th>Amount</th><th>Payment</th><th>Status</th><th>Source</th><th>Date</th></tr></thead><tbody><?php foreach($orders as $order): ?><tr><td><a href="/admin/orders?search=<?= urlencode((string)$order['order_id']) ?>">#<?= $h($order['order_id']) ?></a></td><td><b><?= $h($order['customer_name']) ?></b><small><?= $h($order['customer_email']?:$order['customer_phone']) ?></small></td><td><?= $h($order['product_summary']?:($order['item_count'].' item(s)')) ?></td><td>₹<?= number_format((float)$order['total_amount'],2) ?></td><td><span class="badge <?= $order['payment_status']==='paid'?'b-green':'b-amber' ?>"><?= $h($order['payment_status']==='paid'?'Paid':'Pending Payment') ?></span></td><td><?= $h($labels[$order['status']]??$order['status']) ?></td><td><?= $order['order_source']==='admin'?'<span class="badge b-purple">Admin</span>':'Customer' ?></td><td><?= $h(app_datetime($order['created_at'],'d M Y, H:i')) ?></td></tr><?php endforeach; ?><?php if(!$orders): ?><tr><td colspan="8" class="adm-report-empty">No orders found for this range.</td></tr><?php endif; ?></tbody></table></div></article>
</main></div></div></div></body></html>
