<?php
declare(strict_types=1);
namespace Combos;
final class ComboOfferManager {
 public static function ensureSchema(): void {
  \Database::query("CREATE TABLE IF NOT EXISTS combo_offers (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,title VARCHAR(180) NOT NULL,slug VARCHAR(190) NOT NULL UNIQUE,badge VARCHAR(100) NULL,short_description VARCHAR(500) NULL,description TEXT NULL,banner_image VARCHAR(500) NULL,regular_price DECIMAL(12,2) NOT NULL DEFAULT 0,combo_price DECIMAL(12,2) NOT NULL DEFAULT 0,layout_slot ENUM('large','wide','square') NOT NULL DEFAULT 'square',cta_text VARCHAR(80) NOT NULL DEFAULT 'View Offer',sort_order INT NOT NULL DEFAULT 0,show_on_home TINYINT(1) NOT NULL DEFAULT 1,is_active TINYINT(1) NOT NULL DEFAULT 1,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,KEY idx_combo_home (is_active,show_on_home,sort_order)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
  \Database::query("CREATE TABLE IF NOT EXISTS combo_offer_items (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,combo_offer_id INT UNSIGNED NOT NULL,product_id INT UNSIGNED NOT NULL,quantity INT NOT NULL DEFAULT 1,regular_price DECIMAL(12,2) NOT NULL DEFAULT 0,sort_order INT NOT NULL DEFAULT 0,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,KEY idx_combo_items (combo_offer_id,sort_order),CONSTRAINT fk_combo_items_offer FOREIGN KEY (combo_offer_id) REFERENCES combo_offers(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
 }
 public static function all(bool $public=false): array { self::ensureSchema(); $where=$public?"WHERE c.is_active=1":""; $rows=\Database::rows("SELECT c.*,(SELECT COUNT(*) FROM combo_offer_items ci WHERE ci.combo_offer_id=c.id) item_count FROM combo_offers c $where ORDER BY c.sort_order,c.id DESC"); return $rows; }
 public static function home(): array { self::ensureSchema(); return \Database::rows("SELECT * FROM combo_offers WHERE is_active=1 AND show_on_home=1 ORDER BY FIELD(layout_slot,'large','wide','square'),sort_order,id DESC LIMIT 4"); }
 public static function findBySlug(string $slug): ?array { self::ensureSchema(); $o=\Database::row("SELECT * FROM combo_offers WHERE slug=? AND is_active=1 LIMIT 1",[$slug]); return $o?self::withItems($o):null; }
 public static function find(int $id): ?array { self::ensureSchema(); $o=\Database::row("SELECT * FROM combo_offers WHERE id=?",[$id]); return $o?self::withItems($o):null; }
 private static function withItems(array $o): array { $o['items']=\Database::rows("SELECT ci.*,p.name product_name,p.slug product_slug,(SELECT COALESCE(pi.image_path,pi.url) FROM product_images pi WHERE pi.product_id=p.id AND pi.is_primary=1 LIMIT 1) product_image FROM combo_offer_items ci JOIN products p ON p.id=ci.product_id WHERE ci.combo_offer_id=? ORDER BY ci.sort_order,ci.id",[(int)$o['id']]); return $o; }
 public static function save(array $d, int $id=0): array { self::ensureSchema(); $title=trim((string)($d['title']??'')); $slug=strtolower(trim((string)preg_replace('/[^a-z0-9]+/i','-',(string)($d['slug']??$title)),'-')); if($title===''||$slug==='') return ['ok'=>false,'msg'=>'Title and slug are required.']; $regular=max(0,(float)($d['regular_price']??0));$combo=max(0,(float)($d['combo_price']??0));if($combo<=0)return ['ok'=>false,'msg'=>'Combo price is required.']; $vals=[$title,$slug,trim((string)($d['badge']??'')),trim((string)($d['short_description']??'')),trim((string)($d['description']??'')),trim((string)($d['banner_image']??'')),$regular,$combo,in_array(($d['layout_slot']??''),['large','wide','square'],true)?$d['layout_slot']:'square',trim((string)($d['cta_text']??'View Offer'))?:'View Offer',(int)($d['sort_order']??0),!empty($d['show_on_home'])?1:0,!empty($d['is_active'])?1:0]; if($id){\Database::query("UPDATE combo_offers SET title=?,slug=?,badge=?,short_description=?,description=?,banner_image=?,regular_price=?,combo_price=?,layout_slot=?,cta_text=?,sort_order=?,show_on_home=?,is_active=?,updated_at=NOW() WHERE id=?",[...$vals,$id]);}else{$id=\Database::insert("INSERT INTO combo_offers(title,slug,badge,short_description,description,banner_image,regular_price,combo_price,layout_slot,cta_text,sort_order,show_on_home,is_active,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,NOW())",$vals);} $productIds=array_values(array_unique(array_filter(array_map('intval',(array)($d['product_ids']??[]))))); \Database::query("DELETE FROM combo_offer_items WHERE combo_offer_id=?",[$id]); foreach($productIds as $i=>$pid){\Database::insert("INSERT INTO combo_offer_items(combo_offer_id,product_id,quantity,regular_price,sort_order,created_at) VALUES(?,?,1,0,?,NOW())",[$id,$pid,$i]);} return ['ok'=>true,'id'=>$id]; }
 public static function delete(int $id): void {self::ensureSchema();\Database::query("DELETE FROM combo_offers WHERE id=?",[$id]);}
}
