<?php
$pageTitle=htmlspecialchars((string)$combo['title']).' — Combo Offer';$pageImage=(string)($combo['banner_image']??'');include INCLUDE_PATH.'/partials/head.php';include INCLUDE_PATH.'/partials/header.php';
$saving=max(0,(float)$combo['regular_price']-(float)$combo['combo_price']);
$detailVisible=static fn(string $field):bool=>(int)($combo['show_'.$field.'_detail']??$combo['show_'.$field]??1)===1;
$parseSpecs=static function(string $text):array{$rows=[];foreach(preg_split('/\R/u',$text)?:[] as $line){$line=trim($line);if($line==='')continue;$parts=preg_split('/\s*:\s*/u',$line,2);$rows[]=['label'=>count($parts)>1?$parts[0]:'Specification','value'=>count($parts)>1?$parts[1]:$parts[0]];}return $rows;};
?>
<main class="pd-page combo-pd-page"><div class="container"><nav class="combo-breadcrumb"><a href="/">Home</a><span>›</span><span>Combo Offer</span></nav>
<section class="combo-pd-hero"><div class="combo-pd-gallery"><img src="<?= htmlspecialchars($pageImage?:'/assets/images/RCS%20PRINT%20LOGO.png') ?>" alt="<?= htmlspecialchars((string)$combo['title']) ?>"></div><div class="combo-pd-info">
<?php if($detailVisible('badge')&&!empty($combo['badge'])):?><span class="combo-pd-badge"><?= htmlspecialchars((string)$combo['badge']) ?></span><?php endif;?>
<?php if($detailVisible('title')):?><h1><?= htmlspecialchars((string)$combo['title']) ?></h1><?php endif;?>
<?php $desc=$detailVisible('description')?(string)$combo['description']:($detailVisible('short_description')?(string)$combo['short_description']:'');if($desc!==''):?><p class="combo-pd-description"><?= nl2br(htmlspecialchars($desc)) ?></p><?php endif;?>
<div class="combo-pd-price"><del>₹<?= number_format((float)$combo['regular_price'],2) ?></del><strong>₹<?= number_format((float)$combo['combo_price'],2) ?></strong><span><?= number_format((float)$combo['discount_percent'],2) ?>% OFF</span><b>You save ₹<?= number_format($saving,2) ?></b></div>
<div class="combo-design-box"><h3>Design Option</h3><label><input type="radio" name="combo_design" value="upload" checked onchange="toggleComboDesign()"> Upload Your Design</label><label><input type="radio" name="combo_design" value="rcs" onchange="toggleComboDesign()"> Design by RCS</label><div id="comboUploadBox"><input type="file" id="comboArtwork" accept=".pdf,.ai,.eps,.png,.jpg,.jpeg,.psd,.cdr" onchange="uploadComboArtwork(this)"><small id="comboArtworkStatus">Upload print-ready artwork (maximum configured upload size).</small></div><textarea id="comboDesignBrief" class="fi" rows="3" placeholder="Design brief or special instructions"></textarea></div>
<button class="btn btn-blue btn-full combo-add-btn" id="addComboBtn" onclick="addComboToCart()"><?= $detailVisible('cta')?htmlspecialchars((string)($combo['cta_text']?:'Add to Cart')):'Add to Cart' ?></button><div id="comboCartMsg"></div></div></section>
<section class="combo-included"><h2>Included Items</h2><?php foreach($combo['items'] as $item):?><details class="combo-item-card"><summary><img src="<?= htmlspecialchars((string)($item['product_image']?:'/assets/images/RCS%20PRINT%20LOGO.png')) ?>" alt=""><span><strong><?= htmlspecialchars((string)$item['product_name']) ?></strong><small><?= number_format((int)$item['quantity']) ?> qty</small></span><b>₹<?= number_format((float)$item['regular_price'],2) ?></b><i>⌄</i></summary><div class="combo-item-body"><img src="<?= htmlspecialchars((string)($item['product_image']?:'/assets/images/RCS%20PRINT%20LOGO.png')) ?>" alt=""><div><h3><?= htmlspecialchars((string)$item['product_name']) ?></h3><?php if(!empty($item['product_description'])):?><p><?= nl2br(htmlspecialchars((string)$item['product_description'])) ?></p><?php endif;?><dl><div><dt>Quantity</dt><dd><?= number_format((int)$item['quantity']) ?></dd></div><div><dt>Price</dt><dd>₹<?= number_format((float)$item['regular_price'],2) ?></dd></div></dl></div></div></details><?php endforeach;?>
<?php foreach(($combo['custom_items']??[]) as $item):$specs=$parseSpecs((string)($item['description']??''));?><details class="combo-item-card"><summary><img src="<?= htmlspecialchars((string)($item['thumbnail_path']?:'/assets/images/RCS%20PRINT%20LOGO.png')) ?>" alt=""><span><strong><?= htmlspecialchars((string)$item['item_name']) ?></strong><small><?= number_format((int)($item['quantity']??1)) ?> qty</small></span><b>₹<?= number_format((float)$item['item_price'],2) ?> each</b><i>⌄</i></summary><div class="combo-item-body"><img src="<?= htmlspecialchars((string)($item['thumbnail_path']?:'/assets/images/RCS%20PRINT%20LOGO.png')) ?>" alt=""><div><h3><?= htmlspecialchars((string)$item['item_name']) ?></h3><?php if($specs):?><dl class="combo-spec-list"><?php foreach($specs as $spec):?><div><dt><?= htmlspecialchars($spec['label']) ?></dt><dd><?= htmlspecialchars($spec['value']) ?></dd></div><?php endforeach;?></dl><?php endif;?></div></div></details><?php endforeach;?></section></div></main>
<script>
let comboArtworkId=null;function toggleComboDesign(){document.getElementById('comboUploadBox').hidden=document.querySelector('[name=combo_design]:checked').value!=='upload'}
async function uploadComboArtwork(input){const file=input.files?.[0];if(!file)return;const fd=new FormData();fd.append('artwork',file);const st=document.getElementById('comboArtworkStatus');st.textContent='Uploading…';const r=await fetch('/api/upload/artwork',{method:'POST',headers:{'X-CSRF-TOKEN':APP.csrfToken},body:fd}).then(x=>x.json()).catch(()=>({ok:false,msg:'Upload failed'}));if(!r.ok){st.textContent=r.msg||'Upload failed';return}comboArtworkId=Number(r.artwork_id);st.textContent=`Uploaded: ${r.filename}`}
async function addComboToCart(){const b=document.getElementById('addComboBtn'),choice=document.querySelector('[name=combo_design]:checked').value;if(choice==='upload'&&!comboArtworkId){document.getElementById('comboCartMsg').textContent='Please upload your design file first.';return}b.disabled=true;const r=await fetch('/api/cart/combo',{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-TOKEN':APP.csrfToken},credentials:'same-origin',body:JSON.stringify({combo_offer_id:<?= (int)$combo['id'] ?>,design_choice:choice,design_brief:document.getElementById('comboDesignBrief').value,artwork_id:comboArtworkId})}).then(x=>x.json()).catch(()=>({ok:false,msg:'Could not add combo'}));if(r.ok)location.href='/cart';else{document.getElementById('comboCartMsg').textContent=r.msg||'Could not add combo';b.disabled=false}}
</script><?php include INCLUDE_PATH.'/partials/footer.php'; ?>
